version: "3"

services:
  user-service:
    image: sunilbhadram/newsapp_userservice:v1
    restart: always
    container_name: newsapp-us-docker
    environment:
      HOST_NAME: localhost
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: passw0rd
      MYSQL_URL: jdbc:mysql://localhost:3306/newsapp_db
    network_mode: host
    depends_on: 
      - mysqlservice
      - eureka-server
    ports: 
      - "8080:8080"
            
          
  favourite-service:
    image: sunilbhadram/newsapp_favservice:v1
    restart: always
    container_name: newsapp-fs-docker
    environment:
      MONGO_DATABASE: FavServiceDB
      MONGO_PORT: 27017
      MONGO_HOST: localhost
      HOST_NAME: localhost
    network_mode: host
    depends_on: 
      - mongoservice
      - eureka-server
      - zuul-gateway
      - rabbitmq
    ports: 
      - "8082:8082"
      
  recom-service:
    image: sunilbhadram/newsapp_recomservice:v1
    restart: always
    container_name: newsapp-rs-docker
    environment:
      MONGO_DATABASE: RecomServiceDB
      MONGO_PORT: 27017
      MONGO_HOST: localhost
      HOST_NAME: localhost
    network_mode: host
    depends_on: 
      - mongoservice
      - eureka-server
      - rabbitmq
    ports: 
      - "8081:8081"
      
  ui-service:
    image: sunilbhadram/newsapp_uiservice:v1
    restart: always
    container_name: newsapp-ui-docker
    network_mode: host    
    ports: 
      - "4200:4200"

  eureka-server:
    image: sunilbhadram/eureka-micro-service:v1
    restart: always
    network_mode: host    
    container_name: eureka-docker
    depends_on: 
      - mongoservice
    ports: 
      - "8761:8761"

  zuul-gateway:
    image: sunilbhadram/zuul-micro-service:v1
    restart: always
    network_mode: host    
    container_name: zuul-gateway
    depends_on: 
      - eureka-server
    ports: 
      - "8765:8765"
      
  rabbitmq:
    image: "rabbitmq:management"
    restart: always
    hostname: "rabbit"
    ports:
      - "15672:15672"
      - "5672:5672"
    healthcheck:
      test: "exit 0"
    

  mysqlservice:
    image: mysql:latest
    restart: always
    network_mode: host    
    ports: 
     - "3306:3306"
    container_name: mysql-docker
    environment:
      MYSQL_DATABASE: newsapp_db    
      MYSQL_ROOT_PASSWORD: passw0rd
         

  mongoservice:
    image: mongo:latest
    restart: always
    network_mode: host    
    ports: 
     - "27017:27017"
    container_name: mongo-docker

