spring:
  datasource:
    url: jdbc:mysql://localhost:3306/newsapp_db
    username: root
    password: passw0rd
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
  application:
    name: userservice
server:
  port: 8083
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka